name: Run python application

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    env:
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      TO_EMAIL: ${{ secrets.TO_EMAIL }}
      FROM_EMAIL: ${{ secrets.FROM_EMAIL }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Cache chrome webdriver
      uses: actions/cache@v2
      with:
        path: /home/runner/.local/share/pyppeteer
        key: ${{ runner.os }}-chromewebdriver-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-chromewebdriver-
          ${{ runner.os }}-

    - name: Install dependencies
      run: pip install -r requirements.txt

     - name: Run the iStore script
      run: |
        python iStore.py

    # - name: Run the incredible connection script
    #   run: |
    #     python incredible.py
        
    # - name: Run the btgames script
    #   run: |
    #     python btgames.py
        
    # - name: Run the Game4U script
    #   run: |
    #     python game4u.py

    # - name: Run the koodoo script
    #   run: |
    #     python koodoo.py
    
    # - name: Run the takealot script
    #   run: |
    #     python takealot.py
    
    # - name: Run the Game script
    #   run: |
    #     python game.py

    - name: Commit and push if sent.json changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add .
        git commit -m "Changed Sent Status" || exit 0
        git push