name: Run python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      TO_EMAIL: ${{ secrets.TO_EMAIL }}
      FROM_EMAIL: ${{ secrets.FROM_EMAIL }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Cache chrome webdriver
      uses: actions/cache@v2
      with:
        path: /home/runner/.local/share/pyppeteer
        key: ${{ runner.os }}-chromewebdriver-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-chromewebdriver-
          ${{ runner.os }}-

    - name: Install dependencies
      run: pip install -r requirements.txt
        
    - name: Run the incredible connection script
      run: |
        python incredible.py
        
    - name: Run the Game4U script
      run: |
        python game4u.py

    - name: Run the koodoo script
      run: |
        python koodoo.py
    
    - name: Run the takealot script
      run: |
        python takealot.py
    
    - name: Run the Game script
      run: |
        python game.py